var list = [ {
    fileName : "/home/demoweb/proxy/proxy_module.js", 
    serverAddress : "10.193.251.188",
    serverPort : 9080,
    functionName : "startServer",
    httpApiName : ""
  } , {
    fileName : "/home/demoweb/face/node/face_api_plus/main_module.js",
    serverAddress : "10.193.251.188",
    serverPort : 9081,
    functionName : "startServer",
    httpApiName : "face_api"
  } , {
    fileName : "/home/demoweb/face/node/faceapi_back/main_module.js",
    serverAddress : "10.193.251.188",
    serverPort : 9100,
    functionName : "startServer",
    httpApiName : "face_rec_api"
  } , {
    fileName : "/home/demoweb/face/node/nTrain/main_module.js",
    serverAddress : "10.193.251.188",
    serverPort : 9082,
    functionName : "startServer",
    sigintTrigger : "sigintTriggerFunction",
    httpApiName : "ntrain_api"
  } , {
    fileName : "/home/demoweb/face/node/faceID_api/main_module.js",
    serverAddress : "10.193.251.188",
    serverPort : 9083,
    functionName : "startServer",
    httpApiName : "face_api"
  } , {
    fileName : "/home/demoweb/face/node/faceIdapi_back/main_module.js",
    serverAddress : "10.193.251.188",
    serverPort : 9084,
    functionName : "startServer",
    httpApiName : "face_id_api"
  } , {
    fileName : "/home/demoweb/face/node/nTrain_Id/main_module.js",
    serverAddress : "10.193.251.188",
    serverPort : 9085,
    functionName : "startServer",
    sigintTrigger : "sigintTriggerFunction",
    httpApiName : "ntrain_id"
  } , {
    fileName : "/home/demoweb/face/node/nTrain_Id_test/main_module.js",
    serverAddress : "10.193.251.188",
    serverPort : 9086,
    functionName : "startServer",
    httpApiName : "face_api"
  } , {
    fileName : "/home/demoweb/face/facePairFea/faceapi_back/main_module.js",
    serverAddress : "10.193.251.188",
    serverPort : 9089,
    functionName : "startServer",
    httpApiName : "face_pair_api"
  }
];

exports.list = list;
